title: <p align="center"> Amogh Gadagi </p>


description:
  <p align="center">
  <a href="https://www.linkedin.com/in/amoghgadagi/">LinkedIn</a> |
  <a href="https://github.com/GadagiAmogh">GitHub</a>
  
  <br>   
  I'm currently working as Mechanical Engineer, also studying Machine Learning and Artificial Intelligence.
  <br>
  </p>



theme: jekyll-theme-minimal
